language: ruby
before_install: gem install bundler -v 1.5.1
script: bundle exec rake
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
gemfile:
  - test/gemfiles/Gemfile.rails-3.2.x
  - test/gemfiles/Gemfile.rails-4.0.x
  - test/gemfiles/Gemfile.rails-4.1.x
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: spec/gemfiles/rails-4.1.x.gemfile
  fast_finish: true
