sudo: false
language: ruby
script: bundle exec rake
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - jruby-19mode
gemfile:
  - test/gemfiles/Gemfile.rails-4.2.x
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: spec/gemfiles/rails-4.2.x.gemfile
  fast_finish: true
